// Generated by scripts/gen-types.py – mirrors `supabase gen types`. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.18" };
  public: {
    Tables: {
      activities: {
        Row: {
          id: string;
          workspace_id: string;
          type: string;
          body: string | null;
          company_id: string | null;
          contact_id: string | null;
          deal_id: string | null;
          author_id: string | null;
          occurred_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          type: string;
          body?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          deal_id?: string | null;
          author_id?: string | null;
          occurred_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          type?: string;
          body?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          deal_id?: string | null;
          author_id?: string | null;
          occurred_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "activities_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "activities_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "activities_contact_id_workspace_id_fkey";
            columns: ["contact_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "activities_deal_id_workspace_id_fkey";
            columns: ["deal_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "activities_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      companies: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          org_number: string | null;
          address: string | null;
          postal_code: string | null;
          city: string | null;
          nace_code: string | null;
          nace_description: string | null;
          website: string | null;
          email: string | null;
          phone: string | null;
          notes: string | null;
          owner_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          org_number?: string | null;
          address?: string | null;
          postal_code?: string | null;
          city?: string | null;
          nace_code?: string | null;
          nace_description?: string | null;
          website?: string | null;
          email?: string | null;
          phone?: string | null;
          notes?: string | null;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          org_number?: string | null;
          address?: string | null;
          postal_code?: string | null;
          city?: string | null;
          nace_code?: string | null;
          nace_description?: string | null;
          website?: string | null;
          email?: string | null;
          phone?: string | null;
          notes?: string | null;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "companies_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "companies_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "companies_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      contacts: {
        Row: {
          id: string;
          workspace_id: string;
          company_id: string | null;
          first_name: string;
          last_name: string | null;
          email: string | null;
          phone: string | null;
          title: string | null;
          address: string | null;
          postal_code: string | null;
          city: string | null;
          marketing_consent: boolean;
          marketing_consent_at: string | null;
          notes: string | null;
          owner_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          company_id?: string | null;
          first_name: string;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          title?: string | null;
          address?: string | null;
          postal_code?: string | null;
          city?: string | null;
          marketing_consent?: boolean;
          marketing_consent_at?: string | null;
          notes?: string | null;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          company_id?: string | null;
          first_name?: string;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          title?: string | null;
          address?: string | null;
          postal_code?: string | null;
          city?: string | null;
          marketing_consent?: boolean;
          marketing_consent_at?: string | null;
          notes?: string | null;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contacts_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "contacts_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contacts_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contacts_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      deals: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          value: number;
          currency: string;
          stage_id: string;
          company_id: string | null;
          contact_id: string | null;
          project_id: string | null;
          owner_id: string | null;
          expected_close: string | null;
          closed_at: string | null;
          lost_reason: string | null;
          position: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          value?: number;
          currency?: string;
          stage_id: string;
          company_id?: string | null;
          contact_id?: string | null;
          project_id?: string | null;
          owner_id?: string | null;
          expected_close?: string | null;
          closed_at?: string | null;
          lost_reason?: string | null;
          position?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          title?: string;
          value?: number;
          currency?: string;
          stage_id?: string;
          company_id?: string | null;
          contact_id?: string | null;
          project_id?: string | null;
          owner_id?: string | null;
          expected_close?: string | null;
          closed_at?: string | null;
          lost_reason?: string | null;
          position?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "deals_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "deals_contact_id_workspace_id_fkey";
            columns: ["contact_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "deals_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "deals_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "deals_project_id_workspace_id_fkey";
            columns: ["project_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "deals_stage_id_workspace_id_fkey";
            columns: ["stage_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "pipeline_stages";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "deals_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      invitations: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          role: Database["public"]["Enums"]["member_role"];
          token: string;
          invited_by: string | null;
          created_at: string;
          expires_at: string;
          accepted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          email: string;
          role?: Database["public"]["Enums"]["member_role"];
          token?: string;
          invited_by?: string | null;
          created_at?: string;
          expires_at?: string;
          accepted_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          email?: string;
          role?: Database["public"]["Enums"]["member_role"];
          token?: string;
          invited_by?: string | null;
          created_at?: string;
          expires_at?: string;
          accepted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "invitations_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invitations_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      members: {
        Row: {
          workspace_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["member_role"];
          created_at: string;
        };
        Insert: {
          workspace_id: string;
          user_id: string;
          role?: Database["public"]["Enums"]["member_role"];
          created_at?: string;
        };
        Update: {
          workspace_id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["member_role"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "members_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      pipeline_stages: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          position: number;
          probability: number;
          is_won: boolean;
          is_lost: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          position?: number;
          probability?: number;
          is_won?: boolean;
          is_lost?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          position?: number;
          probability?: number;
          is_won?: boolean;
          is_lost?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pipeline_stages_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          locale: string;
          notify_email: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          locale?: string;
          notify_email?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          locale?: string;
          notify_email?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      project_contacts: {
        Row: { workspace_id: string; project_id: string; contact_id: string; created_at: string };
        Insert: { workspace_id: string; project_id: string; contact_id: string; created_at?: string };
        Update: { workspace_id?: string; project_id?: string; contact_id?: string; created_at?: string };
        Relationships: [
          {
            foreignKeyName: "project_contacts_contact_id_workspace_id_fkey";
            columns: ["contact_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "project_contacts_project_id_workspace_id_fkey";
            columns: ["project_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "project_contacts_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      projects: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          color: string;
          archived: boolean;
          owner_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          color?: string;
          archived?: boolean;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string | null;
          color?: string;
          archived?: boolean;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "projects_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "projects_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "projects_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      task_attachments: {
        Row: {
          id: string;
          workspace_id: string;
          task_id: string;
          path: string;
          name: string;
          size: number;
          mime: string | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          task_id: string;
          path: string;
          name: string;
          size?: number;
          mime?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          task_id?: string;
          path?: string;
          name?: string;
          size?: number;
          mime?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "task_attachments_uploaded_by_fkey";
            columns: ["uploaded_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_attachments_task_id_workspace_id_fkey";
            columns: ["task_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "task_attachments_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      task_comments: {
        Row: {
          id: string;
          workspace_id: string;
          task_id: string;
          author_id: string | null;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          task_id: string;
          author_id?: string | null;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          task_id?: string;
          author_id?: string | null;
          body?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "task_comments_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_comments_task_id_workspace_id_fkey";
            columns: ["task_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "task_comments_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      task_members: {
        Row: { task_id: string; workspace_id: string; user_id: string; added_by: string | null; created_at: string };
        Insert: {
          task_id: string;
          workspace_id: string;
          user_id: string;
          added_by?: string | null;
          created_at?: string;
        };
        Update: {
          task_id?: string;
          workspace_id?: string;
          user_id?: string;
          added_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "task_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_members_added_by_fkey";
            columns: ["added_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_members_task_id_workspace_id_fkey";
            columns: ["task_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "task_members_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      tasks: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          description: string | null;
          due_at: string | null;
          started_at: string | null;
          done_at: string | null;
          assignee_id: string | null;
          company_id: string | null;
          contact_id: string | null;
          deal_id: string | null;
          project_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          description?: string | null;
          due_at?: string | null;
          started_at?: string | null;
          done_at?: string | null;
          assignee_id?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          deal_id?: string | null;
          project_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          title?: string;
          description?: string | null;
          due_at?: string | null;
          started_at?: string | null;
          done_at?: string | null;
          assignee_id?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          deal_id?: string | null;
          project_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_assignee_id_fkey";
            columns: ["assignee_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "tasks_contact_id_workspace_id_fkey";
            columns: ["contact_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "tasks_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_deal_id_workspace_id_fkey";
            columns: ["deal_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "tasks_project_fk";
            columns: ["project_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "tasks_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          org_number: string | null;
          plan: Database["public"]["Enums"]["plan_type"];
          contact_limit: number;
          stripe_customer_id: string | null;
          trial_ends_at: string;
          discount_percent: number;
          discount_until: string | null;
          discount_note: string | null;
          admin_note: string | null;
          suspended_at: string | null;
          billing_interval: string;
          accounting_addon: boolean;
          terms_version: string | null;
          terms_accepted_at: string | null;
          terms_accepted_by: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          org_number?: string | null;
          plan?: Database["public"]["Enums"]["plan_type"];
          contact_limit?: number;
          stripe_customer_id?: string | null;
          trial_ends_at?: string;
          discount_percent?: number;
          discount_until?: string | null;
          discount_note?: string | null;
          admin_note?: string | null;
          suspended_at?: string | null;
          billing_interval?: string;
          accounting_addon?: boolean;
          terms_version?: string | null;
          terms_accepted_at?: string | null;
          terms_accepted_by?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          org_number?: string | null;
          plan?: Database["public"]["Enums"]["plan_type"];
          contact_limit?: number;
          stripe_customer_id?: string | null;
          trial_ends_at?: string;
          discount_percent?: number;
          discount_until?: string | null;
          discount_note?: string | null;
          admin_note?: string | null;
          suspended_at?: string | null;
          billing_interval?: string;
          accounting_addon?: boolean;
          terms_version?: string | null;
          terms_accepted_at?: string | null;
          terms_accepted_by?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "workspaces_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "workspaces_terms_accepted_by_fkey";
            columns: ["terms_accepted_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      accept_invitation: { Args: { p_token: string }; Returns: string };
      create_workspace: { Args: { p_name: string; p_org_number?: string }; Returns: string };
      platform_admin_status: { Args: never; Returns: { is_admin: boolean; has_aal2: boolean }[] };
      admin_workspaces: {
        Args: never;
        Returns: {
          id: string;
          name: string;
          org_number: string | null;
          plan: Database["public"]["Enums"]["plan_type"];
          trial_ends_at: string;
          contact_limit: number;
          discount_percent: number;
          discount_until: string | null;
          discount_note: string | null;
          admin_note: string | null;
          suspended_at: string | null;
          created_at: string;
          owner_email: string | null;
          owner_name: string | null;
          member_count: number;
          contact_count: number;
          last_activity: string | null;
        }[];
      };
      admin_workspace_members: {
        Args: { p_id: string };
        Returns: {
          user_id: string;
          email: string;
          full_name: string | null;
          role: Database["public"]["Enums"]["member_role"];
          joined_at: string;
          last_sign_in_at: string | null;
        }[];
      };
      admin_audit_log: {
        Args: { p_id: string };
        Returns: { created_at: string; admin_email: string | null; changes: Json }[];
      };
      admin_update_workspace: {
        Args: {
          p_id: string;
          p_plan: Database["public"]["Enums"]["plan_type"];
          p_trial_ends_at: string;
          p_contact_limit: number;
          p_discount_percent: number;
          p_discount_until: string | null;
          p_discount_note: string | null;
          p_admin_note: string | null;
          p_suspended: boolean;
        };
        Returns: undefined;
      };
      admin_workspaces_v2: {
        Args: never;
        Returns: {
          id: string;
          name: string;
          org_number: string | null;
          plan: Database["public"]["Enums"]["plan_type"];
          trial_ends_at: string;
          contact_limit: number;
          discount_percent: number;
          discount_until: string | null;
          discount_note: string | null;
          admin_note: string | null;
          suspended_at: string | null;
          created_at: string;
          owner_email: string | null;
          owner_name: string | null;
          member_count: number;
          contact_count: number;
          last_activity: string | null;
          billing_interval: string;
          accounting_addon: boolean;
        }[];
      };
      admin_update_billing: { Args: { p_id: string; p_interval: string; p_addon: boolean }; Returns: undefined };
      accept_terms: { Args: { p_workspace: string; p_version: string }; Returns: undefined };
      my_invitations: {
        Args: never;
        Returns: {
          token: string;
          workspace_name: string;
          role: Database["public"]["Enums"]["member_role"];
          invited_by_name: string | null;
        }[];
      };
    };
    Enums: {
      member_role: "owner" | "admin" | "user";
      plan_type: "trial" | "start" | "bedrift" | "free";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

export type MemberRole = Database["public"]["Enums"]["member_role"];
export type PlanType = Database["public"]["Enums"]["plan_type"];
export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];
