// Generated by scripts/gen-types.py – mirrors `supabase gen types`. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.18" };
  public: {
    Tables: {
      activities: {
        Row: {
          id: string;
          workspace_id: string;
          type: string;
          body: string | null;
          company_id: string | null;
          contact_id: string | null;
          deal_id: string | null;
          author_id: string | null;
          occurred_at: string;
          project_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          type: string;
          body?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          deal_id?: string | null;
          author_id?: string | null;
          occurred_at?: string;
          project_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          type?: string;
          body?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          deal_id?: string | null;
          author_id?: string | null;
          occurred_at?: string;
          project_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "activities_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "activities_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "activities_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "activities_contact_id_workspace_id_fkey";
            columns: ["contact_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "activities_deal_id_workspace_id_fkey";
            columns: ["deal_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "activities_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      automations: {
        Row: {
          id: string;
          workspace_id: string;
          stage_id: string;
          task_title: string;
          due_days: number;
          active: boolean;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          stage_id: string;
          task_title: string;
          due_days?: number;
          active?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          stage_id?: string;
          task_title?: string;
          due_days?: number;
          active?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "automations_stage_id_workspace_id_fkey";
            columns: ["stage_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "pipeline_stages";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "automations_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "automations_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      booking_pages: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          slug: string;
          title: string;
          intro: string | null;
          location: string | null;
          duration_min: number;
          weekdays: number[];
          day_start: string;
          day_end: string;
          buffer_min: number;
          notice_hours: number;
          days_ahead: number;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          slug: string;
          title?: string;
          intro?: string | null;
          location?: string | null;
          duration_min?: number;
          weekdays?: number[];
          day_start?: string;
          day_end?: string;
          buffer_min?: number;
          notice_hours?: number;
          days_ahead?: number;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          slug?: string;
          title?: string;
          intro?: string | null;
          location?: string | null;
          duration_min?: number;
          weekdays?: number[];
          day_start?: string;
          day_end?: string;
          buffer_min?: number;
          notice_hours?: number;
          days_ahead?: number;
          active?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "booking_pages_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      bookings: {
        Row: {
          id: string;
          workspace_id: string;
          page_id: string | null;
          user_id: string;
          starts_at: string;
          ends_at: string;
          name: string;
          email: string;
          phone: string | null;
          company: string | null;
          message: string | null;
          contact_id: string | null;
          task_id: string | null;
          cancel_token: string;
          cancelled_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          page_id?: string | null;
          user_id: string;
          starts_at: string;
          ends_at: string;
          name: string;
          email: string;
          phone?: string | null;
          company?: string | null;
          message?: string | null;
          contact_id?: string | null;
          task_id?: string | null;
          cancel_token?: string;
          cancelled_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          page_id?: string | null;
          user_id?: string;
          starts_at?: string;
          ends_at?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          company?: string | null;
          message?: string | null;
          contact_id?: string | null;
          task_id?: string | null;
          cancel_token?: string;
          cancelled_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "bookings_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      companies: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          org_number: string | null;
          address: string | null;
          postal_code: string | null;
          city: string | null;
          nace_code: string | null;
          nace_description: string | null;
          website: string | null;
          email: string | null;
          phone: string | null;
          notes: string | null;
          custom: Json;
          owner_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          brreg_snapshot: Json | null;
          brreg_status: string | null;
          brreg_checked_at: string | null;
          last_activity_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          org_number?: string | null;
          address?: string | null;
          postal_code?: string | null;
          city?: string | null;
          nace_code?: string | null;
          nace_description?: string | null;
          website?: string | null;
          email?: string | null;
          phone?: string | null;
          notes?: string | null;
          custom?: Json;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          brreg_snapshot?: Json | null;
          brreg_status?: string | null;
          brreg_checked_at?: string | null;
          last_activity_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          org_number?: string | null;
          address?: string | null;
          postal_code?: string | null;
          city?: string | null;
          nace_code?: string | null;
          nace_description?: string | null;
          website?: string | null;
          email?: string | null;
          phone?: string | null;
          notes?: string | null;
          custom?: Json;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          brreg_snapshot?: Json | null;
          brreg_status?: string | null;
          brreg_checked_at?: string | null;
          last_activity_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "companies_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "companies_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "companies_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      contacts: {
        Row: {
          id: string;
          workspace_id: string;
          company_id: string | null;
          first_name: string;
          last_name: string | null;
          email: string | null;
          phone: string | null;
          title: string | null;
          address: string | null;
          postal_code: string | null;
          city: string | null;
          marketing_consent: boolean;
          marketing_consent_at: string | null;
          notes: string | null;
          custom: Json;
          owner_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          last_activity_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          company_id?: string | null;
          first_name: string;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          title?: string | null;
          address?: string | null;
          postal_code?: string | null;
          city?: string | null;
          marketing_consent?: boolean;
          marketing_consent_at?: string | null;
          notes?: string | null;
          custom?: Json;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          last_activity_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          company_id?: string | null;
          first_name?: string;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          title?: string | null;
          address?: string | null;
          postal_code?: string | null;
          city?: string | null;
          marketing_consent?: boolean;
          marketing_consent_at?: string | null;
          notes?: string | null;
          custom?: Json;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          last_activity_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "contacts_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "contacts_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contacts_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contacts_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      custom_fields: {
        Row: {
          id: string;
          workspace_id: string;
          entity: string;
          label: string;
          type: string;
          options: string[];
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          entity: string;
          label: string;
          type: string;
          options?: string[];
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          entity?: string;
          label?: string;
          type?: string;
          options?: string[];
          position?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "custom_fields_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      deals: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          value: number;
          currency: string;
          stage_id: string;
          company_id: string | null;
          contact_id: string | null;
          project_id: string | null;
          owner_id: string | null;
          expected_close: string | null;
          closed_at: string | null;
          lost_reason: string | null;
          custom: Json;
          position: number;
          stage_changed_at: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          value?: number;
          currency?: string;
          stage_id: string;
          company_id?: string | null;
          contact_id?: string | null;
          project_id?: string | null;
          owner_id?: string | null;
          expected_close?: string | null;
          closed_at?: string | null;
          lost_reason?: string | null;
          custom?: Json;
          position?: number;
          stage_changed_at?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          title?: string;
          value?: number;
          currency?: string;
          stage_id?: string;
          company_id?: string | null;
          contact_id?: string | null;
          project_id?: string | null;
          owner_id?: string | null;
          expected_close?: string | null;
          closed_at?: string | null;
          lost_reason?: string | null;
          custom?: Json;
          position?: number;
          stage_changed_at?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "deals_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "deals_contact_id_workspace_id_fkey";
            columns: ["contact_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "deals_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "deals_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "deals_project_id_workspace_id_fkey";
            columns: ["project_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "deals_stage_id_workspace_id_fkey";
            columns: ["stage_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "pipeline_stages";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "deals_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      email_templates: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          subject: string;
          body: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          subject: string;
          body: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          subject?: string;
          body?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "email_templates_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "email_templates_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      external_invoices: {
        Row: {
          workspace_id: string;
          provider: string;
          external_id: string;
          company_id: string | null;
          invoice_number: string | null;
          invoice_date: string | null;
          due_date: string | null;
          amount: number;
          amount_ex_vat: number;
          outstanding: number;
          currency: string;
          is_credit_note: boolean;
          overdue_task_id: string | null;
          synced_at: string;
        };
        Insert: {
          workspace_id: string;
          provider: string;
          external_id: string;
          company_id?: string | null;
          invoice_number?: string | null;
          invoice_date?: string | null;
          due_date?: string | null;
          amount?: number;
          amount_ex_vat?: number;
          outstanding?: number;
          currency?: string;
          is_credit_note?: boolean;
          overdue_task_id?: string | null;
          synced_at?: string;
        };
        Update: {
          workspace_id?: string;
          provider?: string;
          external_id?: string;
          company_id?: string | null;
          invoice_number?: string | null;
          invoice_date?: string | null;
          due_date?: string | null;
          amount?: number;
          amount_ex_vat?: number;
          outstanding?: number;
          currency?: string;
          is_credit_note?: boolean;
          overdue_task_id?: string | null;
          synced_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "external_invoices_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "external_invoices_overdue_task_id_fkey";
            columns: ["overdue_task_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "external_invoices_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      feedback: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string | null;
          kind: string;
          page: string | null;
          message: string;
          handled_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id?: string | null;
          kind?: string;
          page?: string | null;
          message: string;
          handled_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string | null;
          kind?: string;
          page?: string | null;
          message?: string;
          handled_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "feedback_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      inbound_emails: {
        Row: {
          id: string;
          workspace_id: string;
          message_id: string | null;
          from_email: string;
          from_name: string | null;
          to_emails: string[];
          cc_emails: string[];
          external_emails: string[];
          subject: string | null;
          body: string | null;
          sent_at: string;
          author_id: string | null;
          status: string;
          linked_count: number;
          project_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          message_id?: string | null;
          from_email: string;
          from_name?: string | null;
          to_emails?: string[];
          cc_emails?: string[];
          external_emails?: string[];
          subject?: string | null;
          body?: string | null;
          sent_at?: string;
          author_id?: string | null;
          status?: string;
          linked_count?: number;
          project_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          message_id?: string | null;
          from_email?: string;
          from_name?: string | null;
          to_emails?: string[];
          cc_emails?: string[];
          external_emails?: string[];
          subject?: string | null;
          body?: string | null;
          sent_at?: string;
          author_id?: string | null;
          status?: string;
          linked_count?: number;
          project_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "inbound_emails_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "inbound_emails_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      integration_links: {
        Row: { workspace_id: string; provider: string; entity: string; external_id: string; local_id: string };
        Insert: { workspace_id: string; provider: string; entity: string; external_id: string; local_id: string };
        Update: { workspace_id?: string; provider?: string; entity?: string; external_id?: string; local_id?: string };
        Relationships: [
          {
            foreignKeyName: "integration_links_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      integrations: {
        Row: {
          workspace_id: string;
          provider: string;
          credentials: string;
          external_company: string | null;
          last_sync_at: string | null;
          last_error: string | null;
          sync_started_at: string | null;
          connected_by: string | null;
          created_at: string;
        };
        Insert: {
          workspace_id: string;
          provider: string;
          credentials: string;
          external_company?: string | null;
          last_sync_at?: string | null;
          last_error?: string | null;
          sync_started_at?: string | null;
          connected_by?: string | null;
          created_at?: string;
        };
        Update: {
          workspace_id?: string;
          provider?: string;
          credentials?: string;
          external_company?: string | null;
          last_sync_at?: string | null;
          last_error?: string | null;
          sync_started_at?: string | null;
          connected_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "integrations_connected_by_fkey";
            columns: ["connected_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "integrations_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      invitations: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          role: Database["public"]["Enums"]["member_role"];
          token: string;
          invited_by: string | null;
          created_at: string;
          expires_at: string;
          accepted_at: string | null;
          project_ids: string[];
        };
        Insert: {
          id?: string;
          workspace_id: string;
          email: string;
          role?: Database["public"]["Enums"]["member_role"];
          token?: string;
          invited_by?: string | null;
          created_at?: string;
          expires_at?: string;
          accepted_at?: string | null;
          project_ids?: string[];
        };
        Update: {
          id?: string;
          workspace_id?: string;
          email?: string;
          role?: Database["public"]["Enums"]["member_role"];
          token?: string;
          invited_by?: string | null;
          created_at?: string;
          expires_at?: string;
          accepted_at?: string | null;
          project_ids?: string[];
        };
        Relationships: [
          {
            foreignKeyName: "invitations_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invitations_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      lead_forms: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          public_key: string;
          active: boolean;
          owner_id: string | null;
          project_id: string | null;
          create_deal: boolean;
          create_task: boolean;
          ask_phone: boolean;
          ask_company: boolean;
          require_message: boolean;
          title: string | null;
          intro: string | null;
          button_text: string | null;
          thank_you: string | null;
          submissions: number;
          last_submission_at: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          public_key?: string;
          active?: boolean;
          owner_id?: string | null;
          project_id?: string | null;
          create_deal?: boolean;
          create_task?: boolean;
          ask_phone?: boolean;
          ask_company?: boolean;
          require_message?: boolean;
          title?: string | null;
          intro?: string | null;
          button_text?: string | null;
          thank_you?: string | null;
          submissions?: number;
          last_submission_at?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          public_key?: string;
          active?: boolean;
          owner_id?: string | null;
          project_id?: string | null;
          create_deal?: boolean;
          create_task?: boolean;
          ask_phone?: boolean;
          ask_company?: boolean;
          require_message?: boolean;
          title?: string | null;
          intro?: string | null;
          button_text?: string | null;
          thank_you?: string | null;
          submissions?: number;
          last_submission_at?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "lead_forms_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lead_forms_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lead_forms_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "lead_forms_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      mail_connections: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          provider: string;
          account_email: string | null;
          refresh_token: string;
          mail_enabled: boolean;
          calendar_enabled: boolean;
          synced_until: string;
          last_sync_at: string | null;
          last_error: string | null;
          project_id: string | null;
          parent_id: string | null;
          mailbox: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          provider?: string;
          account_email?: string | null;
          refresh_token: string;
          mail_enabled?: boolean;
          calendar_enabled?: boolean;
          synced_until?: string;
          last_sync_at?: string | null;
          last_error?: string | null;
          project_id?: string | null;
          parent_id?: string | null;
          mailbox?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          provider?: string;
          account_email?: string | null;
          refresh_token?: string;
          mail_enabled?: boolean;
          calendar_enabled?: boolean;
          synced_until?: string;
          last_sync_at?: string | null;
          last_error?: string | null;
          project_id?: string | null;
          parent_id?: string | null;
          mailbox?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "mail_connections_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "mail_connections_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      members: {
        Row: {
          workspace_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["member_role"];
          restricted: boolean;
          created_at: string;
        };
        Insert: {
          workspace_id: string;
          user_id: string;
          role?: Database["public"]["Enums"]["member_role"];
          restricted?: boolean;
          created_at?: string;
        };
        Update: {
          workspace_id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["member_role"];
          restricted?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "members_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      pipeline_stages: {
        Row: {
          id: string;
          workspace_id: string;
          pipeline_id: string;
          name: string;
          position: number;
          probability: number;
          is_won: boolean;
          is_lost: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          pipeline_id?: string;
          name: string;
          position?: number;
          probability?: number;
          is_won?: boolean;
          is_lost?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          pipeline_id?: string;
          name?: string;
          position?: number;
          probability?: number;
          is_won?: boolean;
          is_lost?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pipeline_stages_pipeline_fkey";
            columns: ["pipeline_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "pipelines";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "pipeline_stages_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      pipelines: {
        Row: { id: string; workspace_id: string; name: string; position: number; created_at: string };
        Insert: { id?: string; workspace_id: string; name: string; position?: number; created_at?: string };
        Update: { id?: string; workspace_id?: string; name?: string; position?: number; created_at?: string };
        Relationships: [
          {
            foreignKeyName: "pipelines_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      products: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          sku: string | null;
          unit: string;
          unit_price: number;
          vat_rate: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          sku?: string | null;
          unit?: string;
          unit_price?: number;
          vat_rate?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string | null;
          sku?: string | null;
          unit?: string;
          unit_price?: number;
          vat_rate?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "products_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          locale: string;
          notify_email: boolean;
          idle_timeout_minutes: number;
          digest_email: boolean;
          dashboard: Json | null;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          locale?: string;
          notify_email?: boolean;
          idle_timeout_minutes?: number;
          digest_email?: boolean;
          dashboard?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          locale?: string;
          notify_email?: boolean;
          idle_timeout_minutes?: number;
          digest_email?: boolean;
          dashboard?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      project_companies: {
        Row: { workspace_id: string; project_id: string; company_id: string; created_at: string };
        Insert: { workspace_id: string; project_id: string; company_id: string; created_at?: string };
        Update: { workspace_id?: string; project_id?: string; company_id?: string; created_at?: string };
        Relationships: [
          {
            foreignKeyName: "project_companies_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "project_companies_project_id_workspace_id_fkey";
            columns: ["project_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "project_companies_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      project_members: {
        Row: { workspace_id: string; project_id: string; user_id: string; added_by: string | null; created_at: string };
        Insert: { workspace_id: string; project_id: string; user_id: string; added_by?: string | null; created_at?: string };
        Update: { workspace_id?: string; project_id?: string; user_id?: string; added_by?: string | null; created_at?: string };
        Relationships: [
          {
            foreignKeyName: "project_members_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
        ];
      };
      project_contacts: {
        Row: { workspace_id: string; project_id: string; contact_id: string; created_at: string };
        Insert: { workspace_id: string; project_id: string; contact_id: string; created_at?: string };
        Update: { workspace_id?: string; project_id?: string; contact_id?: string; created_at?: string };
        Relationships: [
          {
            foreignKeyName: "project_contacts_contact_id_workspace_id_fkey";
            columns: ["contact_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "project_contacts_project_id_workspace_id_fkey";
            columns: ["project_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "project_contacts_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      projects: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          color: string;
          archived: boolean;
          owner_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          color?: string;
          archived?: boolean;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string | null;
          color?: string;
          archived?: boolean;
          owner_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "projects_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "projects_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "projects_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      push_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent: string | null;
          disabled_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent?: string | null;
          disabled_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          endpoint?: string;
          p256dh?: string;
          auth?: string;
          user_agent?: string | null;
          disabled_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      quote_lines: {
        Row: {
          id: string;
          workspace_id: string;
          quote_id: string;
          position: number;
          product_id: string | null;
          description: string;
          quantity: number;
          unit: string;
          unit_price: number;
          discount_percent: number;
          vat_rate: number;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          quote_id: string;
          position?: number;
          product_id?: string | null;
          description: string;
          quantity?: number;
          unit?: string;
          unit_price?: number;
          discount_percent?: number;
          vat_rate?: number;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          quote_id?: string;
          position?: number;
          product_id?: string | null;
          description?: string;
          quantity?: number;
          unit?: string;
          unit_price?: number;
          discount_percent?: number;
          vat_rate?: number;
        };
        Relationships: [
          {
            foreignKeyName: "quote_lines_quote_id_workspace_id_fkey";
            columns: ["quote_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "quotes";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "quote_lines_product_id_workspace_id_fkey";
            columns: ["product_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "quote_lines_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      quotes: {
        Row: {
          id: string;
          workspace_id: string;
          number: number;
          title: string;
          status: string;
          deal_id: string | null;
          company_id: string | null;
          contact_id: string | null;
          valid_until: string | null;
          intro: string | null;
          terms: string | null;
          total_ex_vat: number;
          total_vat: number;
          total: number;
          public_token: string;
          sent_at: string | null;
          sent_to: string | null;
          viewed_at: string | null;
          view_count: number;
          responded_at: string | null;
          responder_name: string | null;
          response_comment: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          number?: number;
          title: string;
          status?: string;
          deal_id?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          valid_until?: string | null;
          intro?: string | null;
          terms?: string | null;
          total_ex_vat?: number;
          total_vat?: number;
          total?: number;
          public_token?: string;
          sent_at?: string | null;
          sent_to?: string | null;
          viewed_at?: string | null;
          view_count?: number;
          responded_at?: string | null;
          responder_name?: string | null;
          response_comment?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          number?: number;
          title?: string;
          status?: string;
          deal_id?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          valid_until?: string | null;
          intro?: string | null;
          terms?: string | null;
          total_ex_vat?: number;
          total_vat?: number;
          total?: number;
          public_token?: string;
          sent_at?: string | null;
          sent_to?: string | null;
          viewed_at?: string | null;
          view_count?: number;
          responded_at?: string | null;
          responder_name?: string | null;
          response_comment?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quotes_deal_id_workspace_id_fkey";
            columns: ["deal_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "quotes_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "quotes_contact_id_workspace_id_fkey";
            columns: ["contact_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "quotes_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quotes_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      saved_views: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          entity: string;
          name: string;
          query: string;
          shared: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          entity: string;
          name: string;
          query: string;
          shared?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          entity?: string;
          name?: string;
          query?: string;
          shared?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "saved_views_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "saved_views_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      task_attachments: {
        Row: {
          id: string;
          workspace_id: string;
          task_id: string;
          path: string;
          name: string;
          size: number;
          mime: string | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          task_id: string;
          path: string;
          name: string;
          size?: number;
          mime?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          task_id?: string;
          path?: string;
          name?: string;
          size?: number;
          mime?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "task_attachments_uploaded_by_fkey";
            columns: ["uploaded_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_attachments_task_id_workspace_id_fkey";
            columns: ["task_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "task_attachments_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      task_comments: {
        Row: {
          id: string;
          workspace_id: string;
          task_id: string;
          author_id: string | null;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          task_id: string;
          author_id?: string | null;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          task_id?: string;
          author_id?: string | null;
          body?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "task_comments_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_comments_task_id_workspace_id_fkey";
            columns: ["task_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "task_comments_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      task_members: {
        Row: { task_id: string; workspace_id: string; user_id: string; added_by: string | null; created_at: string };
        Insert: {
          task_id: string;
          workspace_id: string;
          user_id: string;
          added_by?: string | null;
          created_at?: string;
        };
        Update: {
          task_id?: string;
          workspace_id?: string;
          user_id?: string;
          added_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "task_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_members_added_by_fkey";
            columns: ["added_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_members_task_id_workspace_id_fkey";
            columns: ["task_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "task_members_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      tasks: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          description: string | null;
          due_at: string | null;
          started_at: string | null;
          done_at: string | null;
          assignee_id: string | null;
          company_id: string | null;
          contact_id: string | null;
          deal_id: string | null;
          project_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          description?: string | null;
          due_at?: string | null;
          started_at?: string | null;
          done_at?: string | null;
          assignee_id?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          deal_id?: string | null;
          project_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          title?: string;
          description?: string | null;
          due_at?: string | null;
          started_at?: string | null;
          done_at?: string | null;
          assignee_id?: string | null;
          company_id?: string | null;
          contact_id?: string | null;
          deal_id?: string | null;
          project_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_assignee_id_fkey";
            columns: ["assignee_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_company_id_workspace_id_fkey";
            columns: ["company_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "tasks_contact_id_workspace_id_fkey";
            columns: ["contact_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "tasks_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_deal_id_workspace_id_fkey";
            columns: ["deal_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "tasks_project_fk";
            columns: ["project_id", "workspace_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id", "workspace_id"];
          },
          {
            foreignKeyName: "tasks_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          org_number: string | null;
          plan: Database["public"]["Enums"]["plan_type"];
          contact_limit: number;
          stripe_customer_id: string | null;
          trial_ends_at: string;
          discount_percent: number;
          discount_until: string | null;
          discount_note: string | null;
          admin_note: string | null;
          suspended_at: string | null;
          billing_interval: string;
          accounting_addon: boolean;
          extra_contact_packs: number;
          terms_version: string | null;
          terms_accepted_at: string | null;
          terms_accepted_by: string | null;
          inbound_token: string | null;
          quote_address: string | null;
          quote_email: string | null;
          quote_phone: string | null;
          quote_bank_account: string | null;
          quote_terms: string | null;
          quote_valid_days: number;
          logo_path: string | null;
          invoice_email: string | null;
          invoice_reference: string | null;
          ordered_at: string | null;
          ordered_by: string | null;
          payment_method: string | null;
          stripe_subscription_id: string | null;
          card_status: string | null;
          card_period_end: string | null;
          pilot_at: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          org_number?: string | null;
          plan?: Database["public"]["Enums"]["plan_type"];
          contact_limit?: number;
          stripe_customer_id?: string | null;
          trial_ends_at?: string;
          discount_percent?: number;
          discount_until?: string | null;
          discount_note?: string | null;
          admin_note?: string | null;
          suspended_at?: string | null;
          billing_interval?: string;
          accounting_addon?: boolean;
          extra_contact_packs?: number;
          terms_version?: string | null;
          terms_accepted_at?: string | null;
          terms_accepted_by?: string | null;
          inbound_token?: string | null;
          quote_address?: string | null;
          quote_email?: string | null;
          quote_phone?: string | null;
          quote_bank_account?: string | null;
          quote_terms?: string | null;
          quote_valid_days?: number;
          logo_path?: string | null;
          invoice_email?: string | null;
          invoice_reference?: string | null;
          ordered_at?: string | null;
          ordered_by?: string | null;
          payment_method?: string | null;
          stripe_subscription_id?: string | null;
          card_status?: string | null;
          card_period_end?: string | null;
          pilot_at?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          org_number?: string | null;
          plan?: Database["public"]["Enums"]["plan_type"];
          contact_limit?: number;
          stripe_customer_id?: string | null;
          trial_ends_at?: string;
          discount_percent?: number;
          discount_until?: string | null;
          discount_note?: string | null;
          admin_note?: string | null;
          suspended_at?: string | null;
          billing_interval?: string;
          accounting_addon?: boolean;
          extra_contact_packs?: number;
          terms_version?: string | null;
          terms_accepted_at?: string | null;
          terms_accepted_by?: string | null;
          inbound_token?: string | null;
          quote_address?: string | null;
          quote_email?: string | null;
          quote_phone?: string | null;
          quote_bank_account?: string | null;
          quote_terms?: string | null;
          quote_valid_days?: number;
          logo_path?: string | null;
          invoice_email?: string | null;
          invoice_reference?: string | null;
          ordered_at?: string | null;
          ordered_by?: string | null;
          payment_method?: string | null;
          stripe_subscription_id?: string | null;
          card_status?: string | null;
          card_period_end?: string | null;
          pilot_at?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "workspaces_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "workspaces_terms_accepted_by_fkey";
            columns: ["terms_accepted_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      accept_invitation: { Args: { p_token: string }; Returns: string };
      create_workspace: { Args: { p_name: string; p_org_number?: string }; Returns: string };
      mail_claim: { Args: { p_ticket: string }; Returns: Json };
      mail_apply: { Args: { p_ticket: string; p_connection: string; p_result: Json }; Returns: number };
      booking_page_public: { Args: { p_slug: string }; Returns: Json };
      booking_create: { Args: { p_slug: string; p_start: string; p_data: Json; p_ip: string }; Returns: Json };
      booking_by_token: { Args: { p_token: string }; Returns: Json };
      booking_cancel: { Args: { p_token: string }; Returns: Json };
      submit_feedback: {
        Args: { p_workspace: string; p_kind: string; p_page: string; p_message: string };
        Returns: string;
      };
      admin_feedback: {
        Args: { p_limit?: number };
        Returns: {
          id: string;
          workspace_id: string;
          workspace: string;
          sender_email: string | null;
          sender_name: string | null;
          kind: string;
          page: string | null;
          message: string;
          handled_at: string | null;
          created_at: string;
          pilot: boolean;
        }[];
      };
      admin_set_pilot: { Args: { p_id: string; p_on: boolean }; Returns: undefined };
      admin_workspace_pilot: { Args: { p_id: string }; Returns: string | null };
      pilot_spots_left: { Args: never; Returns: number };
      platform_admin_status: { Args: never; Returns: { is_admin: boolean; has_aal2: boolean }[] };
      admin_workspaces: {
        Args: never;
        Returns: {
          id: string;
          name: string;
          org_number: string | null;
          plan: Database["public"]["Enums"]["plan_type"];
          trial_ends_at: string;
          contact_limit: number;
          discount_percent: number;
          discount_until: string | null;
          discount_note: string | null;
          admin_note: string | null;
          suspended_at: string | null;
          created_at: string;
          owner_email: string | null;
          owner_name: string | null;
          member_count: number;
          contact_count: number;
          last_activity: string | null;
        }[];
      };
      admin_workspace_members: {
        Args: { p_id: string };
        Returns: {
          user_id: string;
          email: string;
          full_name: string | null;
          role: Database["public"]["Enums"]["member_role"];
          joined_at: string;
          last_sign_in_at: string | null;
        }[];
      };
      admin_audit_log: {
        Args: { p_id: string };
        Returns: { created_at: string; admin_email: string | null; changes: Json }[];
      };
      admin_update_workspace: {
        Args: {
          p_id: string;
          p_plan: Database["public"]["Enums"]["plan_type"];
          p_trial_ends_at: string;
          p_contact_limit: number;
          p_discount_percent: number;
          p_discount_until: string | null;
          p_discount_note: string | null;
          p_admin_note: string | null;
          p_suspended: boolean;
        };
        Returns: undefined;
      };
      admin_workspaces_v2: {
        Args: never;
        Returns: {
          id: string;
          name: string;
          org_number: string | null;
          plan: Database["public"]["Enums"]["plan_type"];
          trial_ends_at: string;
          contact_limit: number;
          discount_percent: number;
          discount_until: string | null;
          discount_note: string | null;
          admin_note: string | null;
          suspended_at: string | null;
          created_at: string;
          owner_email: string | null;
          owner_name: string | null;
          member_count: number;
          contact_count: number;
          last_activity: string | null;
          billing_interval: string;
          accounting_addon: boolean;
        }[];
      };
      admin_workspaces_v3: {
        Args: never;
        Returns: {
          id: string;
          name: string;
          org_number: string | null;
          plan: Database["public"]["Enums"]["plan_type"];
          trial_ends_at: string;
          contact_limit: number;
          discount_percent: number;
          discount_until: string | null;
          discount_note: string | null;
          admin_note: string | null;
          suspended_at: string | null;
          created_at: string;
          owner_email: string | null;
          owner_name: string | null;
          member_count: number;
          contact_count: number;
          last_activity: string | null;
          billing_interval: string;
          accounting_addon: boolean;
          extra_contact_packs: number;
        }[];
      };
      save_integration: {
        Args: { p_workspace: string; p_provider: string; p_credentials: string; p_company: string | null };
        Returns: undefined;
      };
      integration_claim_sync: { Args: { p_workspace: string; p_provider: string }; Returns: boolean };
      integration_synced: {
        Args: { p_workspace: string; p_provider: string; p_error: string | null };
        Returns: undefined;
      };
      admin_update_packs: { Args: { p_id: string; p_packs: number }; Returns: undefined };
      admin_update_billing: { Args: { p_id: string; p_interval: string; p_addon: boolean }; Returns: undefined };
      accept_terms: { Args: { p_workspace: string; p_version: string }; Returns: undefined };
      rotate_inbound_token: { Args: { p_workspace: string }; Returns: string };
      disable_inbound: { Args: { p_workspace: string }; Returns: undefined };
      inbound_try_lock: { Args: Record<string, never>; Returns: boolean };
      ingest_inbound_email: {
        Args: {
          p_token: string;
          p_message_id: string | null;
          p_from_email: string;
          p_from_name: string | null;
          p_to: string[];
          p_cc: string[];
          p_forwarded_from: string | null;
          p_subject: string | null;
          p_body: string | null;
          p_sent_at: string | null;
        };
        Returns: string;
      };
      admin_wipe_workspace_data: { Args: { p_id: string; p_confirm_name: string }; Returns: string[] };
      admin_delete_workspace: { Args: { p_id: string; p_confirm_name: string }; Returns: string[] };
      quote_public: { Args: { p_token: string }; Returns: Json };
      quote_respond: {
        Args: { p_token: string; p_accept: boolean; p_name: string; p_comment: string | null };
        Returns: Json;
      };
      digest_claim: { Args: { p_ticket: string }; Returns: Json };
      lead_submit: { Args: { p_key: string; p_data: Json; p_ip: string }; Returns: Json };
      lead_form_public: { Args: { p_key: string }; Returns: Json };
      brreg_claim: { Args: { p_ticket: string }; Returns: Json };
      order_subscription: {
        Args: {
          p_workspace: string;
          p_plan: Database["public"]["Enums"]["plan_type"];
          p_interval: string;
          p_addon: boolean;
          p_invoice_email: string;
          p_reference: string | null;
        };
        Returns: undefined;
      };
      trial_claim: { Args: { p_ticket: string }; Returns: Json };
      order_subscription_invoice: {
        Args: {
          p_workspace: string;
          p_plan: Database["public"]["Enums"]["plan_type"];
          p_interval: string;
          p_addon: boolean;
          p_invoice_email: string;
          p_reference: string | null;
        };
        Returns: undefined;
      };
      card_checkout_verify: { Args: { p_workspace: string; p_session: string }; Returns: undefined };
      stripe_activate_claim: { Args: { p_ticket: string }; Returns: Json };
      stripe_activate_apply: {
        Args: {
          p_ticket: string;
          p_plan: Database["public"]["Enums"]["plan_type"];
          p_interval: string;
          p_addon: boolean;
          p_email: string;
          p_subscription: string;
          p_customer: string;
          p_period_end: string;
        };
        Returns: undefined;
      };
      stripe_claim: { Args: { p_ticket: string }; Returns: Json };
      stripe_apply: { Args: { p_ticket: string; p_items: Json }; Returns: number };
      calendar_link: { Args: { p_rotate?: boolean }; Returns: string };
      calendar_feed: { Args: { p_token: string }; Returns: Json };
      brreg_snapshots: { Args: { p_ticket: string; p_orgs: string[] }; Returns: Json };
      brreg_apply: { Args: { p_ticket: string; p_items: Json; p_run_started: string }; Returns: number };
      push_subscribe: {
        Args: { p_endpoint: string; p_p256dh: string; p_auth: string; p_user_agent: string | null };
        Returns: undefined;
      };
      queue_push: {
        Args: { p_users: string[]; p_title: string; p_body: string; p_url: string; p_tag: string | null };
        Returns: number;
      };
      queue_test_push: { Args: { p_title: string; p_body: string }; Returns: number };
      push_claim: { Args: { p_ticket: string }; Returns: Json };
      push_gone: { Args: { p_ticket: string; p_endpoints: string[] }; Returns: undefined };
      my_invitations: {
        Args: never;
        Returns: {
          token: string;
          workspace_name: string;
          role: Database["public"]["Enums"]["member_role"];
          invited_by_name: string | null;
        }[];
      };
    };
    Enums: {
      member_role: "owner" | "admin" | "user";
      plan_type: "trial" | "start" | "bedrift" | "free";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

export type MemberRole = Database["public"]["Enums"]["member_role"];
export type PlanType = Database["public"]["Enums"]["plan_type"];
export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];
