"""Generates src/lib/database.types.ts from a compact schema spec.
Keep in sync with supabase/migrations. (Supabase CLI `gen types` gives the same shape.)"""
S, N = "string", "number"
B = "boolean"
# column: (name, ts_type, nullable, has_default)
T = {
 "workspaces": [("id",S,0,1),("name",S,0,0),("org_number",S,1,1),("plan",'Database["public"]["Enums"]["plan_type"]',0,1),("contact_limit",N,0,1),("stripe_customer_id",S,1,1),("trial_ends_at",S,0,1),("created_by",S,1,1),("created_at",S,0,1)],
 "profiles": [("id",S,0,0),("email",S,0,0),("full_name",S,1,1),("locale",S,0,1),("notify_email",B,0,1),("created_at",S,0,1)],
 "members": [("workspace_id",S,0,0),("user_id",S,0,0),("role",'Database["public"]["Enums"]["member_role"]',0,1),("created_at",S,0,1)],
 "invitations": [("id",S,0,1),("workspace_id",S,0,0),("email",S,0,0),("role",'Database["public"]["Enums"]["member_role"]',0,1),("token",S,0,1),("invited_by",S,1,1),("created_at",S,0,1),("expires_at",S,0,1),("accepted_at",S,1,1)],
 "companies": [("id",S,0,1),("workspace_id",S,0,0),("name",S,0,0),("org_number",S,1,1),("address",S,1,1),("postal_code",S,1,1),("city",S,1,1),("nace_code",S,1,1),("nace_description",S,1,1),("website",S,1,1),("email",S,1,1),("phone",S,1,1),("notes",S,1,1),("owner_id",S,1,1),("created_by",S,1,1),("created_at",S,0,1),("updated_at",S,0,1)],
 "contacts": [("id",S,0,1),("workspace_id",S,0,0),("company_id",S,1,1),("first_name",S,0,0),("last_name",S,1,1),("email",S,1,1),("phone",S,1,1),("title",S,1,1),("notes",S,1,1),("owner_id",S,1,1),("created_by",S,1,1),("created_at",S,0,1),("updated_at",S,0,1)],
 "projects": [("id",S,0,1),("workspace_id",S,0,0),("name",S,0,0),("description",S,1,1),("color",S,0,1),("archived",B,0,1),("owner_id",S,1,1),("created_by",S,1,1),("created_at",S,0,1),("updated_at",S,0,1)],
 "project_contacts": [("workspace_id",S,0,0),("project_id",S,0,0),("contact_id",S,0,0),("created_at",S,0,1)],
 "pipeline_stages": [("id",S,0,1),("workspace_id",S,0,0),("name",S,0,0),("position",N,0,1),("probability",N,0,1),("is_won",B,0,1),("is_lost",B,0,1),("created_at",S,0,1)],
 "deals": [("id",S,0,1),("workspace_id",S,0,0),("title",S,0,0),("value",N,0,1),("currency",S,0,1),("stage_id",S,0,0),("company_id",S,1,1),("contact_id",S,1,1),("project_id",S,1,1),("owner_id",S,1,1),("expected_close",S,1,1),("closed_at",S,1,1),("lost_reason",S,1,1),("position",N,0,1),("created_by",S,1,1),("created_at",S,0,1),("updated_at",S,0,1)],
 "tasks": [("id",S,0,1),("workspace_id",S,0,0),("title",S,0,0),("due_at",S,1,1),("done_at",S,1,1),("assignee_id",S,1,1),("company_id",S,1,1),("contact_id",S,1,1),("deal_id",S,1,1),("project_id",S,1,1),("created_by",S,1,1),("created_at",S,0,1),("updated_at",S,0,1)],
 "activities": [("id",S,0,1),("workspace_id",S,0,0),("type",S,0,0),("body",S,1,1),("company_id",S,1,1),("contact_id",S,1,1),("deal_id",S,1,1),("author_id",S,1,1),("occurred_at",S,0,1),("created_at",S,0,1)],
}
# relationships: table -> [(fk_name, [cols], ref_table, [ref_cols])]
def ws(t, col, ref): return (f"{t}_{col}_workspace_id_fkey", [col, "workspace_id"], ref, ["id", "workspace_id"])
def p(t, col): return (f"{t}_{col}_fkey", [col], "profiles", ["id"])
def w(t): return (f"{t}_workspace_id_fkey", ["workspace_id"], "workspaces", ["id"])
R = {
 "workspaces": [p("workspaces","created_by")],
 "profiles": [],
 "members": [p("members","user_id"), w("members")],
 "invitations": [p("invitations","invited_by"), w("invitations")],
 "companies": [p("companies","created_by"), p("companies","owner_id"), w("companies")],
 "contacts": [ws("contacts","company_id","companies"), p("contacts","created_by"), p("contacts","owner_id"), w("contacts")],
 "projects": [p("projects","created_by"), p("projects","owner_id"), w("projects")],
 "project_contacts": [ws("project_contacts","contact_id","contacts"), ws("project_contacts","project_id","projects"), w("project_contacts")],
 "pipeline_stages": [w("pipeline_stages")],
 "deals": [ws("deals","company_id","companies"), ws("deals","contact_id","contacts"), p("deals","created_by"), p("deals","owner_id"), ws("deals","project_id","projects"), ws("deals","stage_id","pipeline_stages"), w("deals")],
 "tasks": [p("tasks","assignee_id"), ws("tasks","company_id","companies"), ws("tasks","contact_id","contacts"), p("tasks","created_by"), ws("tasks","deal_id","deals"), ("tasks_project_fk", ["project_id", "workspace_id"], "projects", ["id", "workspace_id"]), w("tasks")],
 "activities": [p("activities","author_id"), ws("activities","company_id","companies"), ws("activities","contact_id","contacts"), ws("activities","deal_id","deals"), w("activities")],
}
o = ["// Generated by scripts/gen-types.py – mirrors `supabase gen types`. Do not edit by hand.",
     "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];", "",
     "export type Database = {", "  __InternalSupabase: { PostgrestVersion: \"14.18\" };", "  public: {", "    Tables: {"]
for t in sorted(T):
    cols = T[t]
    o.append(f"      {t}: {{")
    o.append("        Row: {" + " ".join(f"{c}: {ty}{' | null' if n else ''};" for c,ty,n,d in cols) + " };")
    o.append("        Insert: {" + " ".join(f"{c}{'?' if (d or n) else ''}: {ty}{' | null' if n else ''};" for c,ty,n,d in cols) + " };")
    o.append("        Update: {" + " ".join(f"{c}?: {ty}{' | null' if n else ''};" for c,ty,n,d in cols) + " };")
    rels = ", ".join("{ foreignKeyName: \"%s\"; columns: [%s]; isOneToOne: false; referencedRelation: \"%s\"; referencedColumns: [%s] }" % (fk, ", ".join(f'"{c}"' for c in cs), rt, ", ".join(f'"{c}"' for c in rc)) for fk,cs,rt,rc in R[t])
    o.append(f"        Relationships: [{rels}];")
    o.append("      };")
o += ["    };", "    Views: { [_ in never]: never };", "    Functions: {",
      "      accept_invitation: { Args: { p_token: string }; Returns: string };",
      "      create_workspace: { Args: { p_name: string; p_org_number?: string }; Returns: string };",
      '      my_invitations: { Args: never; Returns: { token: string; workspace_name: string; role: Database["public"]["Enums"]["member_role"]; invited_by_name: string | null }[] };',
      "    };", "    Enums: {", '      member_role: "owner" | "admin" | "user";', '      plan_type: "trial" | "start" | "bedrift";',
      "    };", "    CompositeTypes: { [_ in never]: never };", "  };", "};", "",
      'export type MemberRole = Database["public"]["Enums"]["member_role"];',
      'export type PlanType = Database["public"]["Enums"]["plan_type"];',
      'export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];', ""]
open("/home/claude/crmforalle/src/lib/database.types.ts","w").write("\n".join(o))
