import { start } from "./lib.mjs";
const v = await start("en-03-new-customer", { lang: "en" });
const P = () => v.page;
v.title("How to add a new customer", "The company comes from the business register – you just add the contact person");
await v.go("/app/bedrifter");
await v.shot({ cursor: [2000, 1400], fade: 0.5 });
v.step("Step 1 of 4", "Open Companies and click «+ New company»", 1.0);
await v.clickOn(P().getByRole("link", { name: /New company/ }).first());
await P().waitForURL("**/app/bedrifter/ny");
await v.settle();
await v.shot({ fade: 0.3 });
const search = P().getByPlaceholder("Search by company name or org. no.");
v.zoom(await v.union([P().getByText("Look up in the business register"), P().locator("input[name=org_number]"), search], 80), 0.9);
v.step("Step 2 of 4", "Search by company name or org. no.", 1.0);
await v.clickOn(search);
await v.typeInto(search, "CIE AS", 1);
const opt = P().getByRole("option").filter({ hasText: /^\s*CIE AS/i }).first();
await opt.waitFor({ timeout: 20000 });
await P().waitForTimeout(400);
await v.shot({ hold: 1.4 });
await v.clickOn(opt);
await P().waitForTimeout(700);
v.zoom(await v.union([P().getByText("Look up in the business register"), P().locator("textarea[name=notes]")], 60), 0.9);
await v.shot({ hold: 0.5 });
v.note("Address, industry and contact details are filled in for you", 3.0);
v.step("Step 3 of 4", "Click «Save»", 0.6);
await v.clickOn(P().getByRole("button", { name: "Save" }));
await P().waitForURL(/\/app\/bedrifter\/[0-9a-f-]{36}/, { timeout: 20000 });
await v.settle();
v.zoom(null, 0.6);
const panel = async () => {
  const l = P().getByText("From Brønnøysund").locator("xpath=ancestor::*[contains(@class,'rounded')][1]");
  return (await l.count()) ? [await v.box(l.first(), 12)] : [];
};
v.autoBlur = panel;
await v.shot({ fade: 0.3, hold: 1.0 });
v.note("The company is added – and AllSeats tells you if its status in the register changes", 2.8);
v.step("Step 4 of 4", "Add the contact person: click «+ New contact»", 1.0);
await v.clickOn(P().getByRole("link", { name: /New contact/ }).first());
await P().waitForURL("**/app/kontakter/ny**");
v.autoBlur = null;
await v.settle();
await v.shot({ fade: 0.3 });
v.zoom(await v.union([P().locator("#k_first"), P().locator("#k_title"), P().locator("#k_phone")], 90), 0.9);
v.note("Fill in name, e-mail, phone and job title", 0.4);
for (const [id, text, every] of [["#k_first", "Kari", 2], ["#k_last", "Nordmann", 2], ["#k_email", "kari@cie.example", 3], ["#k_phone", "+47 900 00 456", 3], ["#k_title", "Managing director", 3]]) {
  const f = P().locator(id); await v.clickOn(f, { dur: 0.6 }); await v.typeInto(f, text, every);
}
v.hold(0.8);
v.zoom(null, 0.7);
await v.clickOn(P().getByRole("button", { name: "Save" }).first());
await P().waitForURL((u) => !u.pathname.endsWith("/ny"), { timeout: 20000 });
await v.settle();
v.autoBlur = panel;
await v.shot({ fade: 0.3, hold: 0.8 });
v.move(await v.center(P().getByText("Kari Nordmann").first()), 1.0);
v.note("Done! Kari Nordmann is now the contact person at CIE AS", 3.4);
v.end();
await v.finish();
