import { start } from "./lib.mjs";
const v = await start("en-04-deals", { lang: "en" });
const P = () => v.page;
const TITLE = "Club socks for the handball team";
v.title("How to work with deals", "From the first enquiry to a won deal");
await v.go("/app/salg");
await v.shot({ cursor: [2000, 1500], fade: 0.5 });
v.step("Step 1 of 4", "Open Sales and click «+ New deal»", 1.0);
await v.clickOn(P().getByRole("link", { name: /New deal/ }).first());
await P().waitForURL("**/app/salg/ny**");
await v.settle();
await v.shot({ fade: 0.3 });
v.zoom(await v.union([P().locator("#d_title"), P().locator("#d_close"), P().locator("#d_stage")], 90), 0.9);
v.step("Step 2 of 4", "Enter a title and value, and choose the customer", 1.0);
const t = P().locator("#d_title"); await v.clickOn(t); await v.typeInto(t, TITLE, 3);
const val = P().locator("#d_value"); await v.clickOn(val, { dur: 0.7 }); await v.typeInto(val, "18000", 1);
const close = P().locator("#d_close"); await v.clickOn(close, { dur: 0.7 }); await close.pressSequentially("20112026");
await v.shot({ hold: 0.6 });
const comp = P().getByPlaceholder("Search by name or org. no. …");
v.zoom(await v.union([P().locator("#d_close"), comp, P().getByPlaceholder("Type to search for a contact …")], 120), 0.9);
await v.clickOn(comp); await v.typeInto(comp, "Skarv", 1);
const o1 = P().getByRole("option", { name: /Skarvvik IL/ }).first(); await o1.waitFor(); await P().waitForTimeout(300);
await v.shot({ hold: 0.6 }); await v.clickOn(o1, { dur: 0.6 }); await P().waitForTimeout(300); await v.shot({ hold: 0.3 });
const pers = P().getByPlaceholder("Type to search for a contact …");
await v.clickOn(pers); await v.typeInto(pers, "Ola", 1);
const o2 = P().getByRole("option", { name: /Ola Berg/ }).first();
for (let i = 0; i < 4; i++) { try { await o2.waitFor({ timeout: 8000 }); break; } catch { await pers.fill(""); await P().waitForTimeout(500); await pers.pressSequentially("Ola", { delay: 80 }); } } await P().waitForTimeout(300);
await v.shot({ hold: 0.6 }); await v.clickOn(o2, { dur: 0.6 }); await P().waitForTimeout(300); await v.shot({ hold: 0.6 });
v.zoom(null, 0.7);
await v.clickOn(P().locator("form:has(#d_title) button[type=submit]").last());
await P().waitForURL((u) => !u.pathname.endsWith("/ny"), { timeout: 20000 });
await v.settle();
await v.shot({ fade: 0.3, hold: 0.6 });
v.note("The deal is created – this is where notes, tasks and quotes come together", 3.0);
v.step("Step 3 of 4", "Drag the deal along the pipeline when something happens", 0.6);
await v.clickOn(P().getByRole("link", { name: "Sales", exact: true }).first());
await P().waitForURL("**/app/salg");
await v.settle();
await v.shot({ fade: 0.3, hold: 0.6 });
const card = P().locator("[draggable=true]", { hasText: TITLE });
const cb = await card.boundingBox();
const zone = P().locator('section[aria-label="Contacted"]');
const zb = await zone.boundingBox();
v.move([Math.round(cb.x + cb.width / 2), Math.round(cb.y + 90)], 0.9);
v.hold(0.3);
v.ev({ drag: { box: [cb.x, cb.y, cb.width, cb.height].map(Math.round), to: [Math.round(zb.x + 210), Math.round(zb.y + zb.height - 150)] }, dur: 1.8 });
await card.dragTo(zone, { targetPosition: { x: 210, y: zb.height - 90 } });
await v.settle();
await v.shot({ fade: 0.15, hold: 1.6 });
v.note("The total and weighted value of each stage update automatically", 3.0);
v.step("Step 4 of 4", "When the customer says yes: open the deal and click «Mark as won»", 0.6);
await v.clickOn(P().getByRole("link", { name: TITLE }).first());
await P().waitForURL(/\/app\/salg\/[0-9a-f-]{36}/);
await v.settle();
await v.shot({ fade: 0.3, hold: 0.6 });
await v.clickOn(P().getByRole("button", { name: /Mark as won/ }));
await v.settle(900);
await v.shot({ fade: 0.2, hold: 0.6 });
v.zoom(await v.union([P().getByText(TITLE).first(), P().getByText("Won", { exact: true }).first()], 120), 0.9);
v.note("Won! The deal now counts in the reports", 3.2);
v.zoom(null, 0.7);
v.end();
await v.finish();
