import { start } from "./lib.mjs";
const v = await start("en-05-quotes", { lang: "en" });
const P = () => v.page;
const DEAL = "Club socks for the football team, 300 pairs";
v.title("How to create and send a quote", "With products, discount and VAT – the customer replies with one click");
await v.go("/app/salg");
await v.shot({ cursor: [2000, 1500], fade: 0.5 });
v.step("Step 1 of 4", "Open the deal and click «+ Create quote»", 1.0);
await v.clickOn(P().getByRole("link", { name: DEAL }).first());
await P().waitForURL(/\/app\/salg\/[0-9a-f-]{36}/);
await v.settle();
await v.shot({ fade: 0.3, hold: 0.6 });
await v.clickOn(P().getByRole("button", { name: /Create quote/ }).first());
await P().waitForURL(/\/app\/tilbud\/[0-9a-f-]{36}/);
await v.settle(900);
await v.shot({ fade: 0.3, hold: 0.6 });
v.note("Customer, contact person and title come from the deal", 2.6);
const intro = P().locator("#q_intro");
v.zoom(await v.union([P().locator("#q_title"), intro], 80), 0.9);
v.step("Step 2 of 4", "Write a short introduction", 0.8);
await v.clickOn(intro);
await v.typeInto(intro, "Thank you for a good meeting! Here is our quote for club socks with your logo.", 6);
v.hold(0.6);
const prod = P().locator('input[placeholder^="Search for a product"]');
v.step("Step 3 of 4", "Add products from your product list", 0.6);
v.zoom(await v.union([P().getByText("Lines", { exact: true }), prod, P().getByText("Total incl. VAT")], 100), 0.9);
await v.clickOn(prod); await v.typeInto(prod, "Sport", 1);
let opt = P().getByRole("option", { name: /Sports sock with logo/ }).first(); await opt.waitFor(); await P().waitForTimeout(300);
await v.shot({ hold: 0.8 }); await v.clickOn(opt); await P().waitForTimeout(500); await v.shot({ hold: 0.5 });
const qty = P().getByLabel("Qty", { exact: true }).first(); await v.clickOn(qty, { dur: 0.7 }); await qty.fill(""); await v.typeInto(qty, "300", 1);
const disc = P().getByLabel("Discount %", { exact: true }).first(); await v.clickOn(disc, { dur: 0.7 }); await v.typeInto(disc, "5", 1);
await P().waitForTimeout(300); await v.shot({ hold: 0.6 });
v.note("Discount and VAT are calculated for you", 2.2);
await v.clickOn(prod, { dur: 0.7 }); await v.typeInto(prod, "Logo", 2);
opt = P().getByRole("option", { name: /Logo design setup/ }).first(); await opt.waitFor(); await P().waitForTimeout(300);
await v.shot({ hold: 0.6 }); await v.clickOn(opt); await P().waitForTimeout(600);
v.zoom(await v.union([P().getByText("Lines", { exact: true }), P().getByText("Total incl. VAT")], 100), 0.7);
await v.shot({ hold: 2.0 });
v.zoom(null, 0.7);
await v.clickOn(P().getByRole("button", { name: "Save quote" }));
await v.settle(1000);
await v.shot({ fade: 0.2, hold: 0.6 });
v.move(await v.center(P().getByRole("link", { name: "Preview PDF" }).or(P().getByRole("button", { name: "Preview PDF" })).first()), 0.9);
v.note("«Preview PDF» shows the quote exactly as the customer gets it – with your logo", 3.0);
v.step("Step 4 of 4", "Check the e-mail address and click «Send quote»", 0.6);
const send = P().getByRole("button", { name: "Send quote" });
v.move(await v.center(P().locator("#s_to")), 1.0);
v.zoom(await v.union([P().getByText("Send quote", { exact: true }).first(), send, P().locator("#s_msg")], 90), 0.9);
v.hold(1.6);
v.move(await v.center(send), 0.8);
v.hold(2.0);
v.zoom(null, 0.7);
v.card({ kicker: "After you send it", text: "You see what the customer does" }, [
  "The customer gets an e-mail with the quote as a PDF and a link.",
  "You see when the customer opens the quote.",
  "They accept or decline with one click – and you are notified straight away.",
], 7);
v.end();
await v.finish();
