import { start } from "./lib.mjs";
const v = await start("en-06-tasks", { lang: "en" });
const P = () => v.page;
const TITLE = "Order sample socks for Skarvvik";
v.title("How to use tasks", "Deadlines, reminders and everything about the customer in one place");
await v.go("/app/oppgaver");
await v.shot({ cursor: [2000, 1500], fade: 0.5 });
const form = P().locator("form", { has: P().locator("input[name=title]") }).first();
const title = form.locator("input[name=title]");
v.zoom(await v.union([title, form.getByRole("button", { name: "Add" })], 100), 0.9);
v.step("Step 1 of 4", "Write what needs doing, and choose a deadline", 1.0);
await v.clickOn(title); await v.typeInto(title, TITLE, 3);
const due = form.locator("input[name=due]"); await v.clickOn(due, { dur: 0.7 }); await due.pressSequentially("09102026");
await v.shot({ hold: 0.8 });
v.step("Step 2 of 4", "Link the task to the customer", 0.8);
const comp = form.getByPlaceholder("Company (optional)");
await v.clickOn(comp); await v.typeInto(comp, "Skarv", 1);
const o1 = P().getByRole("option", { name: /Skarvvik IL/ }).first(); await o1.waitFor(); await P().waitForTimeout(300);
await v.shot({ hold: 0.6 }); await v.clickOn(o1, { dur: 0.6 }); await P().waitForTimeout(300); await v.shot({ hold: 0.3 });
const pers = form.getByPlaceholder(/Contact/);
await v.clickOn(pers);
await P().getByRole("option", { name: /Ola/ }).first().waitFor(); await P().waitForTimeout(400);
await v.shot({ hold: 1.0 });
v.note("The contact field only shows the contacts of the company you chose", 2.6);
await v.clickOn(P().getByRole("option", { name: /Ola Berg/ }).first(), { dur: 0.6 });
await P().waitForTimeout(300); await v.shot({ hold: 0.5 });
await v.clickOn(form.getByRole("button", { name: "Add" }));
await v.settle(900);
v.zoom(null, 0.7);
await v.shot({ fade: 0.2, hold: 1.0 });
v.note("The task is in the list – and on the pages of Skarvvik IL and Ola Berg", 3.0);
v.step("Step 3 of 4", "Open the task to update the status, write notes and attach files", 0.6);
await v.clickOn(P().getByText(TITLE).first());
await P().waitForURL(/\/app\/oppgaver\/[0-9a-f-]{36}/);
await v.settle(900);
await v.shot({ fade: 0.3, hold: 0.8 });
await v.clickOn(P().getByRole("button", { name: "In progress" }));
await v.settle(700); await v.shot({ hold: 0.8 });
const note = P().getByPlaceholder("Write a note or an update …");
await v.clickOn(note); await v.typeInto(note, "Ola wants samples in sizes 39–41 and 42–44.", 5);
await v.clickOn(P().getByRole("button", { name: "Add note" }));
await v.settle(900); await v.shot({ hold: 1.0 });
const file = P().locator("input[type=file]");
const fileBtn = file.locator("xpath=..");
await v.clickOn(fileBtn, { real: false });
await file.setInputFiles(v.dir + "../../Size-list.pdf");
await P().getByText("Size-list.pdf").first().waitFor({ timeout: 20000 });
await v.settle(600);
const fname = P().getByText("Size-list.pdf").first();
v.move(await v.center(fname), 0.8);
await v.shot({ hold: 0.4 });
v.zoom(await v.union([P().getByText("Attachments", { exact: true }).first(), fname, fileBtn], 120), 0.9);
v.note("Attachments: PDF, images, Word, Excel and more – up to 25 MB", 3.0);
v.zoom(null, 0.7);
v.step("Step 4 of 4", "See your tasks in your calendar: Account and security → Calendar", 0.6);
await v.clickOn(P().getByRole("link", { name: "Account and security" }).first());
await P().waitForURL("**/app/konto**");
await v.settle();
await v.shot({ fade: 0.3 });
const kal = P().getByRole("heading", { name: "Calendar", exact: true });
v.move(await v.center(kal), 1.0);
v.zoom(await v.union([kal, kal.locator("xpath=following::button[1]")], 120), 0.9);
v.note("The link works with Google Calendar, Outlook and iPhone", 3.4);
v.zoom(null, 0.7);
v.end();
await v.finish();
