import { createRequire } from "node:module";
import fs from "node:fs";
const require = createRequire(new URL("../../../package.json", import.meta.url));
const { createClient } = require("@supabase/supabase-js");
const root = new URL("..", import.meta.url).pathname;
const env = Object.fromEntries(fs.readFileSync(root + ".env", "utf8").trim().split("\n").map((l) => l.split(/=(.*)/s).slice(0, 2)));
const db = createClient("https://lzhqaxjlhatexerxmtxn.supabase.co", "sb_publishable_hgERd6vRSgnHMZb8hr6r2A_M3GVzqk9", { auth: { persistSession: false } });
await db.auth.signInWithPassword({ email: env.DEMO_EMAIL, password: env.DEMO_PASSWORD });
const { data, error } = await db.storage.from("attachments").remove(process.argv.slice(2));
console.log("removed", data?.length, error?.message ?? "");
