import { start } from "./lib.mjs";
const v = await start("04-salg");
const P = () => v.page;
const TITLE = "Klubbsokker til håndballaget";

v.title("Slik jobber du med salg", "Fra første henvendelse til vunnet salg");
await v.go("/app/salg");
await v.shot({ cursor: [2000, 1500], fade: 0.5 });
v.step("Steg 1 av 4", "Åpne Salg og trykk «+ Nytt salg»", 1.0);
await v.clickOn(P().getByRole("link", { name: /Nytt salg/ }).first());
await P().waitForURL("**/app/salg/ny**");
await v.settle();
await v.shot({ fade: 0.3 });

v.zoom(await v.union([P().locator("#d_title"), P().locator("#d_close"), P().locator("#d_stage")], 90), 0.9);
v.step("Steg 2 av 4", "Skriv tittel og verdi, og velg kunde", 1.0);
const t = P().locator("#d_title");
await v.clickOn(t);
await v.typeInto(t, TITLE, 3);
const val = P().locator("#d_value");
await v.clickOn(val, { dur: 0.7 });
await v.typeInto(val, "18000", 1);
const close = P().locator("#d_close");
await v.clickOn(close, { dur: 0.7 });
await close.pressSequentially("20112026");
await v.shot({ hold: 0.6 });

const comp = P().getByPlaceholder("Søk på navn eller org.nr. …");
v.zoom(await v.union([P().locator("#d_close"), comp, P().getByPlaceholder("Skriv for å søke etter kontakt …")], 120), 0.9);
await v.clickOn(comp);
await v.typeInto(comp, "Skarv", 1);
const o1 = P().getByRole("option", { name: /Skarvvik IL/ }).first();
await o1.waitFor();
await P().waitForTimeout(300);
await v.shot({ hold: 0.6 });
await v.clickOn(o1, { dur: 0.6 });
await P().waitForTimeout(300);
await v.shot({ hold: 0.3 });
const pers = P().getByPlaceholder("Skriv for å søke etter kontakt …");
await v.clickOn(pers);
await v.typeInto(pers, "Ola", 1);
const o2 = P().getByRole("option", { name: /Ola Berg/ }).first();
await o2.waitFor();
await P().waitForTimeout(300);
await v.shot({ hold: 0.6 });
await v.clickOn(o2, { dur: 0.6 });
await P().waitForTimeout(300);
await v.shot({ hold: 0.6 });
v.zoom(null, 0.7);
const save = P().locator("form:has(#d_title) button[type=submit]").last();
await v.clickOn(save);
await P().waitForURL((u) => !u.pathname.endsWith("/ny"), { timeout: 20000 });
await v.settle();
await v.shot({ fade: 0.3, hold: 0.6 });
v.note("Salget er opprettet – her samler du notater, oppgaver og tilbud", 3.0);

v.step("Steg 3 av 4", "Dra salget videre i salgstrakten når noe skjer", 0.6);
await v.clickOn(P().getByRole("link", { name: "Salg", exact: true }).first());
await P().waitForURL("**/app/salg");
await v.settle();
await v.shot({ fade: 0.3, hold: 0.6 });
const card = P().locator("[draggable=true]", { hasText: TITLE });
const cb = await card.boundingBox();
const zone = P().locator('section[aria-label="Kontaktet"]');
const zb = await zone.boundingBox();
v.move([Math.round(cb.x + cb.width / 2), Math.round(cb.y + 90)], 0.9);
v.hold(0.3);
const drop = [Math.round(zb.x + 210), Math.round(zb.y + zb.height - 150)];
v.ev({ drag: { box: [cb.x, cb.y, cb.width, cb.height].map(Math.round), to: drop }, dur: 1.8 });
await card.dragTo(zone, { targetPosition: { x: 210, y: zb.height - 90 } });
await v.settle();
await v.shot({ fade: 0.15, hold: 1.6 });
v.note("Summen og den vektede verdien i hver fase oppdateres automatisk", 3.0);

v.step("Steg 4 av 4", "Når kunden sier ja: åpne salget og trykk «Merk som vunnet»", 0.6);
await v.clickOn(P().getByRole("link", { name: TITLE }).first());
await P().waitForURL(/\/app\/salg\/[0-9a-f-]{36}/);
await v.settle();
await v.shot({ fade: 0.3, hold: 0.6 });
const won = P().getByRole("button", { name: /Merk som vunnet/ });
await v.clickOn(won);
await v.settle(900);
await v.shot({ fade: 0.2, hold: 0.6 });
v.zoom(await v.union([P().getByText(TITLE).first(), P().getByText("Vunnet", { exact: true }).first()], 120), 0.9);
v.note("Vunnet! Salget teller nå med i rapportene", 3.2);
v.zoom(null, 0.7);
v.end();
await v.finish();
